@baseUrl = http://localhost:5028

### Raiz da API
GET {{baseUrl}}/api

# -------- USUÁRIO ---------

### Criar usuário
POST {{baseUrl}}/api/usuarios/cadastrar
Content-Type: application/json

{
  "nome": "Brayan Matheus",
  "email": "brayan@email.com"
}

### Listar todos os usuários
GET {{baseUrl}}/api/usuarios/listar

### Listar usuário por ID
GET {{baseUrl}}/api/usuarios/4

### Atualizar usuário por id
PUT {{baseUrl}}/api/usuarios/atualizar/4
Content-Type: application/json

{
  "nome": "Brayan Atualizado",
  "email": "brayannovo@email.com"
}

### Remover usuário
DELETE {{baseUrl}}/api/usuarios/remover/{id}


# -------- CATEGORIA ---------

### Criar categoria
POST {{baseUrl}}/api/categorias/cadastrar
Content-Type: application/json

{
  "nome": "Conferir estoques de lojas"
}

### Listar todas as categorias
GET {{baseUrl}}/api/categorias/listar

### Listar categoria por ID
GET {{baseUrl}}/api/categorias/{id}

### Atualizar categoria por ID
PUT {{baseUrl}}/api/categorias/atualizar/{id}
Content-Type: application/json

{
  "nome": "Urgência"
}

### Remover categoria
DELETE {{baseUrl}}/api/categorias/remover/{id}

# -------- TAREFAS ---------

### Cadastrar Tarefas
POST {{baseUrl}}/api/tarefas/cadastrar
Content-Type: application/json

{
  "titulo": "Fazer exames",
  "descricao": "Realizar exames médicos",
  "concluida": true,
  "usuarioId": 2,
  "categoriaId": 5
}

### Listar todas as tarefas
GET {{baseUrl}}/api/tarefas/listar

### Listar tarefa por ID
GET  {{baseUrl}}/api/tarefas/{id}

### Atualizar tarefa por ID
PUT {{baseUrl}}/api/tarefas/atualizar/{id}
Content-Type: application/json

{
  "titulo": "Fazer exames",
  "descricao": "Realizar exames médicos",
  "concluida": true,
  "usuarioId": 5,
  "categoriaId": 5
}

### Deletar tarefa
DELETE {{baseUrl}}/api/tarefas/remover/{id}